# Generated by Django 4.2.3 on 2023-08-10 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEssay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('current_questions', models.IntegerField(blank=True, null=True)),
                ('prePaes', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomEssayQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('custom_essay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.customessay')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MathType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypesEssayCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('custom_essay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='essay_custom', to='api.customessay')),
                ('type_essays', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_essay_custom', to='api.mathtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserEssayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('questionNumber', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserEssayConfigTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('essay_types', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_Essay_Config_types', to='api.mathtype')),
                ('users_essasy_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_Essay_Config_types', to='api.useressayconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserQuestionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('state', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answeressayuser',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answeressayuser',
            name='essay',
        ),
        migrations.RemoveField(
            model_name='question',
            name='essay',
        ),
        migrations.RemoveField(
            model_name='users',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='users',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='users',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='users',
            name='linkedin_token',
        ),
        migrations.AddField(
            model_name='answer',
            name='questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='api.question'),
        ),
        migrations.AddField(
            model_name='answeressayuser',
            name='answers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_essay_user', to='api.answer'),
        ),
        migrations.AddField(
            model_name='answeressayuser',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answeressayuser',
            name='time_essay',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='right',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='answer', through='api.AnswerEssayUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answeressayuser',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_essay_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Essay',
        ),
        migrations.AddField(
            model_name='userquestionstate',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_question_state', to='api.question'),
        ),
        migrations.AddField(
            model_name='userquestionstate',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_question_state', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useressayconfig',
            name='essays_types',
            field=models.ManyToManyField(blank=True, related_name='user_Essay_Config', through='api.UserEssayConfigTypes', to='api.mathtype'),
        ),
        migrations.AddField(
            model_name='useressayconfig',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_Essay_Config', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customessayquestion',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
        migrations.AddField(
            model_name='customessay',
            name='type_essay',
            field=models.ManyToManyField(blank=True, related_name='custom_type_essay', through='api.TypesEssayCustom', to='api.mathtype'),
        ),
        migrations.AddField(
            model_name='customessay',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='essay_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answeressayuser',
            name='essays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_essay_user', to='api.customessay'),
        ),
        migrations.AddField(
            model_name='question',
            name='type_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_type', to='api.mathtype'),
        ),
        migrations.AddField(
            model_name='question',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='question_user', through='api.UserQuestionState', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='essay',
            field=models.ManyToManyField(blank=True, related_name='answer', through='api.AnswerEssayUser', to='api.customessay'),
        ),
    ]
