# Generated by Django 4.2.3 on 2023-08-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_useressayconfig_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
