# Generated by Django 4.2.3 on 2023-10-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_achievement_remove_prepaesquestion_custom_essay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dificult',
            field=models.TextField(blank=True, null=True),
        ),
    ]
