# Generated by Django 4.2.3 on 2023-10-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_achievement_created_alter_achievement_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionstate',
            name='is_modify',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
