# Generated by Django 4.2.3 on 2023-10-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userquestionstate_is_modify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionstate',
            name='is_modify',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
