# Generated by Django 4.2.3 on 2023-10-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_achievement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
