# Generated by Django 4.2.1 on 2023-05-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_essay_time_essay_answeressayuser_time_essay'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='chat_messages',
            field=models.ManyToManyField(blank=True, related_name='users', to='api.chatmessage'),
        ),
    ]
