# Generated by Django 4.2.1 on 2023-05-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_chatmessage_users_chat_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='chat_messages',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
