# Generated by Django 4.2.3 on 2023-07-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_useressayconfig_userquestions_useressayconfigtypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='useressayconfig',
            name='essays',
            field=models.ManyToManyField(blank=True, related_name='user_Essay_Config', through='api.UserEssayConfigTypes', to='api.essay'),
        ),
    ]
